### PR TITLE
Allow for fetch options

### LINKED ISSUE #22: how to add custom flag to header?
because my auth server need special flag in http request head, but the code in here:

https://github.com/adambrgmn/react-oauth-flow/blob/f7cb4949a106a1f574eb12dc1bdf4f8b7f71ecb2/src/OauthReceiver/index.js#L81

looks like cannot change outside the library,  so , how to change it?

### PR DESCRIPTION
**Pull request by jwright**
This PR allows for the fetch args to be set via a prop for the `OAuthReceiver` component. This makes the component a little more general by allowing different services to override the default fetch options when fetching from the token service.

For example, the Facebook token service (`https://graph.facebook.com/v3.0/oauth/access_token`) requires a `GET` request but the Dropbox token service (`https://api.dropboxapi.com/oauth2/token`) requires a `POST`. This prop would allow the client to change the defaults.

This would also allow for additional headers to be set or the default `Content-Type` to be changed.

Closes #22

### CODE REVIEW

**Comment by jwright** [comment]
@adambrgmn Is there anyway we can get this merged or reviewed? Let me know if there is anything I can do to help facilitate this at all.

**Comment by adambrgmn** [comment]
Hi Jamie!
Sorry for my late reply!
I have been on vacation for a while and will be for a few more days. So I will have to wait with the review a few more days!

But thanks a lot for your PRs, I'm very happy about them!

**Comment by jwright** [comment]
@adambrgmn No worries! Enjoy your vacation!

**Comment by adambrgmn** [comment]
Hi @jwright! Once again, thanks for both your PRs 😃 
These contributions is actually the first contributions ever to any of my repos, so it's quite exciting for me!

**Comment by adambrgmn** [comment]
Hi again,
I noticed that the release failed for some reason (guessing outdated deps). I'm gonna look into it asap and update the dev env and your contributions will be published.

**Pull request merged**
